site_name: DotDev
#site_description:
site_author: Wojciech Nowicki
site_url: https://wnowicki.dev
repo_url: https://github.com/wnowicki/dotdev
repo_name: wnowicki/dotdev
copyright: 2026, Wojciech Nowicki

nav:
  - Home: index.md
  - GIT: git.md
  - MacOS: macos.md

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  # - git-authors
  # - git-revision-date-localized:
  #     type: date # timeago
  #     enable_creation_date: true
  #     fallback_to_build_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wnowicki

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
